# Generated by Django 2.2.13 on 2021-03-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corfogeneratecode', '0003_auto_20201214_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorfoCodeMappingContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_content', models.IntegerField(default=0, unique=True)),
                ('content', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
