# Generated by Django 2.2.13 on 2021-03-04 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corfogeneratecode', '0004_corfocodemappingcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='corfocodeuser',
            name='mapping_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapping_content', to='corfogeneratecode.CorfoCodeMappingContent'),
        ),
        migrations.AlterUniqueTogether(
            name='corfocodeuser',
            unique_together={('user', 'mapping_content')},
        ),
        migrations.AlterIndexTogether(
            name='corfocodeuser',
            index_together={('user', 'mapping_content')},
        ),
        migrations.RemoveField(
            model_name='corfocodeuser',
            name='course',
        ),
    ]
