# Generated by Django 2.2.19 on 2021-04-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corfogeneratecode', '0007_auto_20210406_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorfoCodeInstitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_institution', models.IntegerField(default=0, unique=True)),
                ('institution', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
