# Generated by Django 2.2.19 on 2021-04-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corfogeneratecode', '0008_corfocodeinstitution'),
    ]

    operations = [
        migrations.AddField(
            model_name='corfocodeuser',
            name='corfo_save',
            field=models.BooleanField(default=True),
        ),
    ]
