# Generated by Django 2.2.19 on 2021-04-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corfogeneratecode', '0009_corfocodeuser_corfo_save'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corfocodeuser',
            name='corfo_save',
            field=models.BooleanField(default=False),
        ),
    ]
