# Generated by Django 2.2.19 on 2021-04-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corfogeneratecode', '0010_auto_20210413_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corfocodeuser',
            name='code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
