# Generated by Django 2.2.24 on 2023-05-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corfogeneratecode', '0011_auto_20210413_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='corfocodeuser',
            name='rut',
            field=models.CharField(default='', max_length=30),
        ),
    ]
